[package]
name = "wasi-core"
version = "0.1.0"
authors = ["The Cranelift Project Developers"]
license = "Apache-2.0 WITH LLVM-exception"
description = "Experimental WASI API bindings for Rust"
edition = "2018"
repository = "https://github.com/CraneStation/wasi-core"
readme = "README.md"

[dependencies]

[badges]
maintenance = { status = "experimental" }
